{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubenab.fullname" . }}
  labels:
{{ include "kubenab.labels" . | indent 4 }}
rules:
{{ toYaml .Values.rbac.role.rules }}
{{- end }}
