apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubenab.fullname" . }}
  labels:
{{ include "kubenab.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
{{ include "kubenab.labels" . | indent 4 }}
